# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227bb60221dc6a15b7aad72b2fae797b0ef7a1113dd5c84dcbe7b4d1296915a964f57a6e27008ac21bc7fa1069285070abcec2bc95fec7bdd7325eeac85f4014

test:
  secret_key_base: e225513bbc2aaffd55b056b90f8918590ab24e31abb5317864cd7658514d06d163fa56020e696ee4bfcf643154be8c675344774f8d027e151185119437938005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
